// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet.Data;

#nullable disable

namespace dotnet.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20230302231229_CreateProductsTable")]
    partial class CreateProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("dotnet.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Km")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TownName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("cityId")
                        .HasColumnType("int");

                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "iste",
                            Km = 53811,
                            ModelName = "harum",
                            Price = 197352f,
                            Text = "Aut quasi ipsa quaerat non. Aperiam qui et aliquid. Commodi sed rerum quo sit amet dolores nostrum quas dicta.",
                            Title = "tenetur",
                            TownName = "est",
                            Year = 2016,
                            cityId = 62,
                            memberId = 123458
                        },
                        new
                        {
                            Id = 2,
                            CityName = "nihil",
                            Km = 10728,
                            ModelName = "aut",
                            Price = 737042f,
                            Text = "Animi velit quidem reprehenderit. Fugiat rerum odio et. Qui et dolorem. Sed molestiae libero quae voluptatem sunt cumque quia quis. Aperiam quos non fuga sit iusto. Qui quia molestiae.",
                            Title = "consequatur",
                            TownName = "pariatur",
                            Year = 1995,
                            cityId = 46,
                            memberId = 123458
                        },
                        new
                        {
                            Id = 3,
                            CityName = "numquam",
                            Km = 44819,
                            ModelName = "qui",
                            Price = 267125f,
                            Text = "Aliquam dolorum eos omnis veniam ullam dignissimos ut. Et autem ea nesciunt. Maiores architecto dolor totam blanditiis quae voluptatem quos. Nobis expedita rerum dolores animi fugit et repudiandae. Nostrum doloremque et ex molestiae.",
                            Title = "ut",
                            TownName = "quasi",
                            Year = 2010,
                            cityId = 35,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 4,
                            CityName = "numquam",
                            Km = 20327,
                            ModelName = "nihil",
                            Price = 493470f,
                            Text = "Dolores eos eligendi pariatur rerum reiciendis et ipsum. Unde aspernatur distinctio. İste ut dolor impedit corrupti explicabo ut. Eligendi totam pariatur possimus dolores corrupti perspiciatis pariatur et. Ea voluptatem rerum earum consequatur non molestiae praesentium.",
                            Title = "sit",
                            TownName = "pariatur",
                            Year = 2015,
                            cityId = 60,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 5,
                            CityName = "tenetur",
                            Km = 54117,
                            ModelName = "ut",
                            Price = 947468f,
                            Text = "Ut quia corporis error aperiam. Minus id natus sapiente. Totam dolore voluptas et totam quia ut. Delectus et officiis at soluta suscipit vel harum ducimus doloribus.",
                            Title = "voluptatem",
                            TownName = "aut",
                            Year = 1991,
                            cityId = 66,
                            memberId = 123456
                        },
                        new
                        {
                            Id = 6,
                            CityName = "id",
                            Km = 93106,
                            ModelName = "reiciendis",
                            Price = 355994f,
                            Text = "Possimus nostrum voluptas atque dicta molestias esse nemo. Sed aut soluta deleniti laudantium eos aut expedita non. Quibusdam et fugit distinctio. Ad a tempora itaque mollitia amet facilis natus rem velit. Enim consequuntur quasi a sit optio.",
                            Title = "dicta",
                            TownName = "sed",
                            Year = 2020,
                            cityId = 21,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 7,
                            CityName = "dolor",
                            Km = 90669,
                            ModelName = "in",
                            Price = 980527f,
                            Text = "Autem facilis placeat quasi voluptas quasi. Quia minima officiis. Animi recusandae error consectetur blanditiis adipisci tenetur. Nobis excepturi et qui. Voluptate soluta recusandae.",
                            Title = "voluptas",
                            TownName = "modi",
                            Year = 2000,
                            cityId = 22,
                            memberId = 123458
                        },
                        new
                        {
                            Id = 8,
                            CityName = "labore",
                            Km = 81792,
                            ModelName = "laborum",
                            Price = 673977f,
                            Text = "Eum officia dolorem voluptate praesentium porro magnam aperiam. Voluptatum non id neque quidem quaerat iusto provident alias ab. Et quia asperiores.",
                            Title = "dignissimos",
                            TownName = "et",
                            Year = 2017,
                            cityId = 46,
                            memberId = 123456
                        },
                        new
                        {
                            Id = 9,
                            CityName = "rerum",
                            Km = 43144,
                            ModelName = "ut",
                            Price = 964703f,
                            Text = "Amet voluptatum cupiditate. İpsam velit fuga eos nobis. Qui et temporibus consectetur fuga quia vel debitis.",
                            Title = "occaecati",
                            TownName = "iusto",
                            Year = 2021,
                            cityId = 40,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 10,
                            CityName = "rerum",
                            Km = 9460,
                            ModelName = "aut",
                            Price = 471425f,
                            Text = "Magni ipsum aut eligendi voluptatibus. Hic corrupti iure sunt provident aut possimus neque. Dolore sapiente dolores molestiae praesentium. Eligendi qui expedita omnis amet.",
                            Title = "eaque",
                            TownName = "velit",
                            Year = 2003,
                            cityId = 45,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 11,
                            CityName = "eum",
                            Km = 88856,
                            ModelName = "veritatis",
                            Price = 809749f,
                            Text = "Natus non qui aut et aspernatur commodi vel in. Consequatur eveniet officiis ducimus. Qui accusamus eligendi temporibus animi itaque natus molestias sunt. Tempora necessitatibus labore qui. Molestiae aliquam in.",
                            Title = "in",
                            TownName = "harum",
                            Year = 1993,
                            cityId = 72,
                            memberId = 123458
                        },
                        new
                        {
                            Id = 12,
                            CityName = "sed",
                            Km = 88632,
                            ModelName = "dolores",
                            Price = 586025f,
                            Text = "Tenetur temporibus ducimus odit pariatur alias similique provident suscipit. Sint fuga repudiandae quia dicta quae at. Commodi illo veniam sapiente laudantium ipsa nostrum sit deserunt iusto. Enim mollitia accusantium iusto.",
                            Title = "suscipit",
                            TownName = "molestias",
                            Year = 2009,
                            cityId = 54,
                            memberId = 123456
                        },
                        new
                        {
                            Id = 13,
                            CityName = "cum",
                            Km = 97388,
                            ModelName = "voluptatem",
                            Price = 682426f,
                            Text = "Voluptatem sed dicta dolor. Provident nemo ipsa qui dolores minus tenetur nihil et error. Commodi nostrum veniam et aut ea possimus perferendis voluptatem enim. Quia animi repellendus et. Vero temporibus dolores asperiores minima. Doloribus asperiores veritatis autem optio quo possimus.",
                            Title = "sunt",
                            TownName = "voluptas",
                            Year = 2008,
                            cityId = 1,
                            memberId = 123458
                        },
                        new
                        {
                            Id = 14,
                            CityName = "illo",
                            Km = 83144,
                            ModelName = "perferendis",
                            Price = 920966f,
                            Text = "Explicabo dolorem est unde facilis tempora. Commodi quidem beatae esse. Cum qui ducimus nihil ratione qui veritatis. Culpa soluta maxime qui aut. Consectetur libero atque laudantium cum necessitatibus.",
                            Title = "non",
                            TownName = "molestias",
                            Year = 2016,
                            cityId = 60,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 15,
                            CityName = "nostrum",
                            Km = 37394,
                            ModelName = "velit",
                            Price = 672280f,
                            Text = "Quas voluptatem aliquid et quidem sit consectetur assumenda. Similique et ut omnis sequi aut est nemo. Sit dolor est quia rem. Magni nesciunt deleniti suscipit quos quae est itaque.",
                            Title = "dignissimos",
                            TownName = "autem",
                            Year = 2015,
                            cityId = 70,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 16,
                            CityName = "reiciendis",
                            Km = 41499,
                            ModelName = "aliquid",
                            Price = 593563f,
                            Text = "Alias reprehenderit maxime voluptatem et. Repellendus atque culpa veritatis velit inventore facere eius veritatis. Et magnam aliquam eum minus delectus. Quia nemo sunt quos et modi expedita dolore placeat.",
                            Title = "dolor",
                            TownName = "doloremque",
                            Year = 1999,
                            cityId = 71,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 17,
                            CityName = "qui",
                            Km = 37924,
                            ModelName = "omnis",
                            Price = 446983f,
                            Text = "Omnis repellendus blanditiis consequuntur consequatur et impedit. Officiis sint expedita tenetur saepe nemo enim sed porro. Ut doloremque qui. Explicabo quo est vero ratione laudantium at.",
                            Title = "molestiae",
                            TownName = "perspiciatis",
                            Year = 2008,
                            cityId = 7,
                            memberId = 123456
                        },
                        new
                        {
                            Id = 18,
                            CityName = "nam",
                            Km = 91780,
                            ModelName = "et",
                            Price = 839286f,
                            Text = "Consequatur cupiditate sed dolor veritatis quaerat velit. Consequatur occaecati dolor tenetur ea libero accusantium. Vel aut perferendis magni vel est optio maiores hic. Et sunt tenetur fugiat impedit odit aspernatur ut.",
                            Title = "sint",
                            TownName = "voluptate",
                            Year = 1994,
                            cityId = 44,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 19,
                            CityName = "ipsam",
                            Km = 5627,
                            ModelName = "saepe",
                            Price = 127928f,
                            Text = "Ullam sit nihil. Et neque maxime. Veniam modi voluptatum est dolorem voluptatibus maxime. Qui quo inventore.",
                            Title = "incidunt",
                            TownName = "maiores",
                            Year = 1990,
                            cityId = 23,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 20,
                            CityName = "earum",
                            Km = 96931,
                            ModelName = "et",
                            Price = 675750f,
                            Text = "Rerum ullam vel ut aut. İste non incidunt delectus. İnventore aut neque repudiandae est molestiae omnis repudiandae voluptatum nam. Culpa consequuntur eos est temporibus qui fuga incidunt illo nulla. Qui itaque nulla nemo eum sed et temporibus dicta reiciendis. Quibusdam ut iure ut odio ipsam mollitia et et.",
                            Title = "quia",
                            TownName = "omnis",
                            Year = 1995,
                            cityId = 27,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 21,
                            CityName = "nesciunt",
                            Km = 5266,
                            ModelName = "sint",
                            Price = 191766f,
                            Text = "Soluta repellat voluptas aut temporibus repellat. Commodi adipisci quibusdam blanditiis. Ut delectus molestiae autem consequatur quia voluptatem ut et.",
                            Title = "consequatur",
                            TownName = "libero",
                            Year = 2013,
                            cityId = 12,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 22,
                            CityName = "vel",
                            Km = 5853,
                            ModelName = "fugit",
                            Price = 540304f,
                            Text = "Ex aut in facilis et amet blanditiis officiis. Possimus ad veritatis qui. Rerum vitae nobis molestias dolorum. Est praesentium eaque doloremque voluptatem reprehenderit occaecati ut quia fugiat. Eveniet vero est harum. Et pariatur consequatur rerum minima doloribus et et.",
                            Title = "voluptatem",
                            TownName = "provident",
                            Year = 2007,
                            cityId = 81,
                            memberId = 123458
                        },
                        new
                        {
                            Id = 23,
                            CityName = "unde",
                            Km = 81344,
                            ModelName = "sit",
                            Price = 917966f,
                            Text = "Omnis deleniti ut commodi. Nemo eligendi distinctio vel occaecati non necessitatibus aut totam quo. Delectus veritatis est suscipit consequatur. Quas quisquam et. Est sint totam et quisquam sit minus deserunt est quis.",
                            Title = "laudantium",
                            TownName = "et",
                            Year = 2012,
                            cityId = 8,
                            memberId = 123456
                        },
                        new
                        {
                            Id = 24,
                            CityName = "non",
                            Km = 32074,
                            ModelName = "voluptatem",
                            Price = 710828f,
                            Text = "Maiores quis quas eum. Dolorum sequi voluptatem eveniet aut. Cum non fuga.",
                            Title = "repudiandae",
                            TownName = "officia",
                            Year = 2004,
                            cityId = 67,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 25,
                            CityName = "doloribus",
                            Km = 63499,
                            ModelName = "nobis",
                            Price = 527854f,
                            Text = "Et ea molestiae voluptatem atque. Sapiente assumenda est et dolore. Sed quam illo ut a. Et similique blanditiis fugit et nostrum. Consequatur eligendi quidem enim animi odit eum.",
                            Title = "atque",
                            TownName = "praesentium",
                            Year = 2013,
                            cityId = 46,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 26,
                            CityName = "ullam",
                            Km = 30566,
                            ModelName = "nobis",
                            Price = 971980f,
                            Text = "Dolor eos nam ipsa necessitatibus. Totam eligendi possimus necessitatibus aut quod. Occaecati neque omnis non omnis totam odit deserunt facere. İd consequatur cum. Eveniet neque laborum iste.",
                            Title = "et",
                            TownName = "id",
                            Year = 2023,
                            cityId = 51,
                            memberId = 123456
                        },
                        new
                        {
                            Id = 27,
                            CityName = "est",
                            Km = 87857,
                            ModelName = "iste",
                            Price = 674284f,
                            Text = "Rerum dolore fuga. Earum dolore assumenda dignissimos qui ex explicabo laborum maxime accusantium. Debitis doloribus asperiores qui ut blanditiis illum ut soluta perferendis. Assumenda recusandae amet amet.",
                            Title = "et",
                            TownName = "optio",
                            Year = 1994,
                            cityId = 43,
                            memberId = 123456
                        },
                        new
                        {
                            Id = 28,
                            CityName = "illo",
                            Km = 477,
                            ModelName = "sit",
                            Price = 676000f,
                            Text = "At nemo officiis consequuntur similique rerum voluptatibus assumenda. Optio voluptates aliquam sunt nesciunt quidem. Molestiae provident totam error voluptates. Quod repellendus omnis deleniti. Laudantium dolores fugiat et accusamus atque. Est voluptatibus qui at beatae doloremque id.",
                            Title = "veniam",
                            TownName = "sed",
                            Year = 2021,
                            cityId = 2,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 29,
                            CityName = "aut",
                            Km = 53434,
                            ModelName = "esse",
                            Price = 223917f,
                            Text = "Reiciendis pariatur odit iure eaque ut. Ut quo nihil quibusdam nihil ut quia qui. Reiciendis distinctio ducimus ipsa dolorem.",
                            Title = "sequi",
                            TownName = "distinctio",
                            Year = 2009,
                            cityId = 69,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 30,
                            CityName = "laudantium",
                            Km = 56607,
                            ModelName = "atque",
                            Price = 323377f,
                            Text = "Eum dolor quasi sed maiores eum quam deserunt fugit rerum. Dolorem autem labore ipsa. Officiis distinctio veritatis dolore facere pariatur et.",
                            Title = "autem",
                            TownName = "ex",
                            Year = 1997,
                            cityId = 68,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 31,
                            CityName = "sed",
                            Km = 29149,
                            ModelName = "iste",
                            Price = 110346f,
                            Text = "Voluptatem placeat autem ducimus rem dolores commodi ex provident. Ut necessitatibus aliquam iusto non earum. Voluptatem qui et deserunt delectus voluptatum. Qui nostrum et est sed autem. Et corrupti repudiandae aperiam et.",
                            Title = "ratione",
                            TownName = "odio",
                            Year = 1994,
                            cityId = 77,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 32,
                            CityName = "aut",
                            Km = 32108,
                            ModelName = "quam",
                            Price = 618210f,
                            Text = "Architecto consequuntur quia aperiam qui molestiae sit illum blanditiis. Cumque iste voluptas veritatis fuga. Aut et non sint qui repudiandae modi maxime vel omnis.",
                            Title = "cum",
                            TownName = "ipsa",
                            Year = 2001,
                            cityId = 68,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 33,
                            CityName = "dolores",
                            Km = 56773,
                            ModelName = "iste",
                            Price = 394007f,
                            Text = "Voluptatem suscipit rerum vel laboriosam beatae facilis consequatur dolores. Qui vel voluptatem. Laboriosam cum corrupti. Eum repellat et repellat aut est repudiandae. Nam voluptatem et labore tempore et voluptatem corporis veniam.",
                            Title = "modi",
                            TownName = "consequatur",
                            Year = 2022,
                            cityId = 31,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 34,
                            CityName = "architecto",
                            Km = 74564,
                            ModelName = "voluptas",
                            Price = 476262f,
                            Text = "Dolores asperiores officia eum. Nobis minus iure molestiae. Error rerum iure amet enim assumenda occaecati perspiciatis debitis. Et aut expedita praesentium non possimus similique. Repudiandae explicabo magnam. Eius soluta ex quidem sunt ut id deserunt.",
                            Title = "mollitia",
                            TownName = "enim",
                            Year = 1997,
                            cityId = 18,
                            memberId = 123456
                        },
                        new
                        {
                            Id = 35,
                            CityName = "ut",
                            Km = 51458,
                            ModelName = "repellendus",
                            Price = 399616f,
                            Text = "Omnis at voluptatem sed voluptatem explicabo. Accusamus et facere laborum fuga rem. Voluptatem id non nulla ut. Consequatur illo aspernatur explicabo. Corporis ut soluta enim est eos quisquam ut eos. Veritatis quia possimus et aliquam.",
                            Title = "aut",
                            TownName = "est",
                            Year = 2023,
                            cityId = 3,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 36,
                            CityName = "rem",
                            Km = 50404,
                            ModelName = "vero",
                            Price = 512855f,
                            Text = "Dicta aperiam sed rerum iste sed. Voluptate dolor in saepe omnis perspiciatis minima temporibus. Consequatur aliquid enim impedit necessitatibus ipsum in sed in. Quia sint incidunt. Ut quo autem non error.",
                            Title = "vitae",
                            TownName = "dolor",
                            Year = 2021,
                            cityId = 69,
                            memberId = 123456
                        },
                        new
                        {
                            Id = 37,
                            CityName = "vero",
                            Km = 85897,
                            ModelName = "est",
                            Price = 463067f,
                            Text = "Natus quibusdam reprehenderit ut quo corrupti laborum repellat voluptas. Harum rem fugit nesciunt hic distinctio praesentium. Modi deleniti dolores qui autem quae temporibus temporibus facilis vel. İpsum vel non nam. Cupiditate laboriosam eligendi officiis. Sed dignissimos sed quisquam nihil esse tempora.",
                            Title = "nemo",
                            TownName = "explicabo",
                            Year = 1991,
                            cityId = 68,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 38,
                            CityName = "recusandae",
                            Km = 68511,
                            ModelName = "voluptates",
                            Price = 948467f,
                            Text = "Magnam delectus dolor doloremque omnis voluptatem. İusto et incidunt eaque voluptatum explicabo omnis facilis odit. Ad necessitatibus dolorem explicabo natus nihil inventore doloribus quibusdam. Rerum inventore et nihil vel quia et. Dolore quibusdam minus sit iusto eligendi quo est soluta. Deserunt pariatur reprehenderit aut.",
                            Title = "possimus",
                            TownName = "et",
                            Year = 2010,
                            cityId = 21,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 39,
                            CityName = "facilis",
                            Km = 68018,
                            ModelName = "nesciunt",
                            Price = 610152f,
                            Text = "Labore quod ut sed veniam quis laborum aliquam. İn vitae maxime voluptatibus expedita. Mollitia voluptates et eum tenetur.",
                            Title = "voluptatibus",
                            TownName = "omnis",
                            Year = 2023,
                            cityId = 77,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 40,
                            CityName = "sequi",
                            Km = 78222,
                            ModelName = "debitis",
                            Price = 695431f,
                            Text = "Sed amet occaecati provident velit. Beatae et earum aperiam ad sint porro ex laborum dolores. Corrupti quia laboriosam dolor officia consequatur repellat necessitatibus iste. Quidem nostrum dolorem nobis occaecati. Voluptas aut dolores eum beatae. Laudantium eaque odit facere ut.",
                            Title = "et",
                            TownName = "tempora",
                            Year = 2010,
                            cityId = 58,
                            memberId = 123458
                        },
                        new
                        {
                            Id = 41,
                            CityName = "excepturi",
                            Km = 59758,
                            ModelName = "adipisci",
                            Price = 486407f,
                            Text = "Ullam distinctio aut eligendi architecto et provident aut. Non ut nisi perferendis et at. At molestiae iusto. Magni quaerat quas consequatur rerum.",
                            Title = "accusamus",
                            TownName = "pariatur",
                            Year = 2016,
                            cityId = 30,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 42,
                            CityName = "ut",
                            Km = 79479,
                            ModelName = "quam",
                            Price = 837297f,
                            Text = "Libero ut velit et omnis excepturi non cumque tenetur quos. Autem et illum. Eos hic omnis aliquam omnis. İusto neque culpa et fugiat. Voluptas quis ex iusto accusantium sit adipisci officiis.",
                            Title = "nam",
                            TownName = "autem",
                            Year = 2010,
                            cityId = 57,
                            memberId = 123458
                        },
                        new
                        {
                            Id = 43,
                            CityName = "quo",
                            Km = 85347,
                            ModelName = "voluptatem",
                            Price = 140612f,
                            Text = "Quisquam neque tenetur. Dignissimos aut quaerat. Aut dolor sit iure asperiores asperiores vero quasi assumenda. Autem enim quaerat dicta eius ea rerum quo suscipit voluptatibus.",
                            Title = "dicta",
                            TownName = "voluptatem",
                            Year = 2003,
                            cityId = 45,
                            memberId = 123458
                        },
                        new
                        {
                            Id = 44,
                            CityName = "blanditiis",
                            Km = 15400,
                            ModelName = "facilis",
                            Price = 708177f,
                            Text = "Consectetur possimus eos. Alias magni ut. Ut molestiae non necessitatibus iure aspernatur doloribus et. Qui qui ipsam voluptatem. Et sit omnis eius laudantium enim magnam. Et magni facere facere quae ut consectetur quaerat.",
                            Title = "laboriosam",
                            TownName = "consequatur",
                            Year = 1995,
                            cityId = 72,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 45,
                            CityName = "asperiores",
                            Km = 60103,
                            ModelName = "quod",
                            Price = 533449f,
                            Text = "Magnam magnam et doloribus molestiae atque magnam architecto. Autem laudantium rerum dolores enim sequi aliquid. Qui illum quo repellat.",
                            Title = "veniam",
                            TownName = "provident",
                            Year = 1999,
                            cityId = 56,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 46,
                            CityName = "ipsa",
                            Km = 6859,
                            ModelName = "dignissimos",
                            Price = 398877f,
                            Text = "Amet veritatis ut. Accusamus qui ipsa cupiditate nostrum harum aut exercitationem perspiciatis quia. Porro odit ipsa dolorem enim incidunt inventore.",
                            Title = "commodi",
                            TownName = "a",
                            Year = 2023,
                            cityId = 1,
                            memberId = 123456
                        },
                        new
                        {
                            Id = 47,
                            CityName = "hic",
                            Km = 64020,
                            ModelName = "saepe",
                            Price = 585416f,
                            Text = "Dolore qui corporis sit consequuntur distinctio. Nihil ut repellat quidem et et ea. Neque reprehenderit rem laudantium tempore fuga.",
                            Title = "odio",
                            TownName = "non",
                            Year = 2017,
                            cityId = 18,
                            memberId = 123458
                        },
                        new
                        {
                            Id = 48,
                            CityName = "voluptatum",
                            Km = 472,
                            ModelName = "cumque",
                            Price = 543627f,
                            Text = "Recusandae tempora dolorem enim. Praesentium culpa libero accusantium rerum quaerat. Quia cupiditate non asperiores.",
                            Title = "vero",
                            TownName = "dolorem",
                            Year = 2019,
                            cityId = 79,
                            memberId = 123459
                        },
                        new
                        {
                            Id = 49,
                            CityName = "vitae",
                            Km = 14342,
                            ModelName = "laboriosam",
                            Price = 578547f,
                            Text = "Officia sapiente odit corrupti nihil quisquam est quam repellendus earum. Cupiditate a quia consectetur nisi natus. Eum nisi sit voluptatem impedit et aliquam laborum illo ea. Porro atque et omnis earum quas voluptatum.",
                            Title = "qui",
                            TownName = "eaque",
                            Year = 2018,
                            cityId = 66,
                            memberId = 123457
                        },
                        new
                        {
                            Id = 50,
                            CityName = "aut",
                            Km = 82175,
                            ModelName = "id",
                            Price = 294331f,
                            Text = "Autem eligendi commodi. Vel aliquam ea exercitationem illo. Qui dolores reiciendis architecto cumque voluptates. Deserunt facilis debitis totam eveniet facere earum quia. İpsum vero aperiam dolorum dolor et odit est placeat. Nisi molestiae libero et.",
                            Title = "magni",
                            TownName = "animi",
                            Year = 2000,
                            cityId = 9,
                            memberId = 123457
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
